### ISSUE TITLE
Server side Errors on Client side

### ISSUE THREAD

**Issue by wltdaniel** [chrissainty/PolicyBasedAuthWithBlazor#2]
I tried to register already a registered account,nothing happens on the UI side unless you view it
on console logs,how can we capture these errors on UI side as well?

![image](https://user-images.githubusercontent.com/31033831/62159721-10de3e00-b31b-11e9-9f30-b9cecd240fae.png)

**Comment by chrissainty** [comment]
I’m using the `PostJsonAsync` extension method, [here](https://github.com/chrissainty/PolicyBasedAuthWithBlazor/blob/c2a2e3bcaeabebc965ab291311ae7f7a31dc6b6e/src/ClientSideBlazor.Client/Services/AuthService.cs#L27), which assumes a success response. 

If you swap to the standard `PostAsync` method then you can manage non-success codes, something like this.

```csharp
var stringContent = new StringContent(JsonSerializer.Serialize(registerModel), Encoding.UTF8, "application/json");
var response = await _httpClient.PostAsync("api/accounts", stringContent);

if (response.StatusCode == System.Net.HttpStatusCode.BadRequest)
{
    // Handle bad request
}
```
