### ISSUE TITLE
AuthorizeView using policies in Navbar

### ISSUE THREAD

**Issue by ghost** [chrissainty/PolicyBasedAuthWithBlazor#8]
Guessing this is a Blazor-wide thing, but I can't get policies to work at all in the Navbar.razor.
Roles working just fine...
Any insight would be really handy,
Cheers,
T

**Comment by ghost** [comment]
...sorry, should have clarified - Navbar.razor can't see the Policies.cs file... Tried @using statements in _Host, MainLayout, and navbar itself. Am I missing something (other than fluency in .net)?

**Comment by chrissainty** [comment]
Could you provide an example of your code? This is definitely possible.

**Comment by jollysod** [comment]
Hi Chris, thanks for getting back to me.
Here's the code:
From NavMenu.razor - first one referencing the definition directly from Startup.cs working, second results in 

> 'The name 'Policies' does not exist in the current context'

```
        <AuthorizeView Policy="CanViewAdminNavbar">
            <li class="nav-item px-3">
                <NavLink class="nav-link" href="/administration">
                    <span class="oi oi-account-login" aria-hidden="true"></span> Admin
                </NavLink>
            </li>
        </AuthorizeView>
        <AuthorizeView Policy="@Policies.CanManage">
            <li class="nav-item px-3">
                <NavLink class="nav-link" href="/administration">
                    <span class="oi oi-account-login" aria-hidden="true"></span> Policies - Admin
                </NavLink>
            </li>
        </AuthorizeView>
```

...and the code from Startup.cs - 
```
            services.AddAuthorizationCore(config =>
            {
                config.AddPolicy(Policies.IsAdmin, Policies.IsAdminPolicy());
                config.AddPolicy(Policies.CanManage, Policies.CanManagePolicy());
                config.AddPolicy("CanViewAdminNavbar", policy => policy.RequireRole("Admin", "Manager"));
            });
```

...and finally from Policies.cs - 
```
namespace DataAccesslibrary.Authorization
{
    public static class Policies
    {
        public const string IsAdmin = "IsAdmin";
        public const string CanManage = "CanManage";

        public static AuthorizationPolicy IsAdminPolicy()
        {
            return new AuthorizationPolicyBuilder().RequireAuthenticatedUser()
                                                   .RequireRole("Admin")
                                                   .Build();
        }

        public static AuthorizationPolicy CanManagePolicy()
        {
            return new AuthorizationPolicyBuilder().RequireAuthenticatedUser()
                                                   .RequireRole("Admin", "Manager")
                                                   .Build();
        }
    }
}
```

Both _IsAdmin_ and  _CanManage_ working fine when referenced directly from a ~.razor file containing @page ref. using either `Policy="@Policies.IsAdmin" ` or `Policy="@Policies.CanManage"`

Anything obvoiusly off with the code?
Cheers,
T

**Comment by chrissainty** [comment]
The first difference I would rule out is the use of the `@` in the second example.

So instead of
```
 <AuthorizeView Policy="@Policies.CanManage">
```
try
```
 <AuthorizeView Policy="Policies.CanManage">
```
You shouldn't need the `@` symbol... I think. :-)

I don't think the fact it's working on a page component is anything to focus on. The `Page` directive is only used by the router, it's ignored by everything else.

It does feel that it's something like a missing using statement. Could you double-check that by using the full class name, something like this?

```
 <AuthorizeView Policy="@DataAccesslibrary.Authorization.Policies.CanManage">
```

**Comment by jollysod** [comment]
Thanks ever so much Chris - although removing the @ didn't work, using the full class name did.
T

**Comment by chrissainty** [comment]
That's great news, glad we got to the bottom of it.
