### ISSUE TITLE
any reason to not user RevalidatingServerAuthenticationStateProvider from blazor

### ISSUE THREAD

**Issue by bradtwurst** [chrissainty/PolicyBasedAuthWithBlazor#9]
It appears that the [server side state provider](https://github.com/chrissainty/PolicyBasedAuthWithBlazor/blob/b608b51fab7025b8ef75cd8e3cecc5f383bf44b9/src/ServerSideBlazor/Areas/Identity/RevalidatingAuthenticationStateProvider.cs#L19) in your repo is basically the same implementation as the [provider in core library](https://github.com/dotnet/aspnetcore/blob/5e49fc336e4464711ff2a8db2e00b9bafb518c78/src/Components/Server/src/Circuits/RevalidatingServerAuthenticationStateProvider.cs#L17)

Is there any general reason that normal auth scenarios would need to re-implement this provider?

**Comment by chrissainty** [comment]
In all honesty, I can't remember why it's there. It could have been that there was a bug at the time I wrote this or I might have been testing something and included it by mistake.

But the answer to your question is no, you don't need reimplement this provider for standard scenarios.
